apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-nginx001
  labels:
    app: demo-nginx001
spec:
  replicas: 1
  template:
    metadata:
      name: demo-nginx001
      labels:
        app: demo-nginx001
    spec:
      imagePullSecrets:
        - name: test-secret
      containers:
        - name: demo-nginx001
          image: ovpn.tool1314.com/libraryprivate/nginx:latest
          imagePullPolicy: Always
      restartPolicy: Always
  selector:
    matchLabels:
      app: demo-nginx001
